spring.application.name=MiniProject2

spring.profiles.active=local
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20

file.upload-dir=uploads/menu-images
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB