/**
 * 백엔드 연동 전 화면 개발용 더미 매장 데이터 (총 30개 — 페이지네이션·카테고리 필터 테스트용)
 * 형태는 GET /api/stores 응답(data 배열)과 동일하게 맞춤 (03_REST_API_설계서 기준)
 *
 * - id 1: dummy_data.sql의 stores + store_details 1번 매장 그대로 (description 포함)
 * - id 2~30: 카테고리 필터·페이지네이션 테스트용으로 추가한 가상 매장 (dummy_data.sql에는 매장이 1개뿐)
 * - imageUrl: 전부 null — 이미지가 없을 때 카드의 플레이스홀더 처리를 확인하기 위함
 * - description, rating, reviewCount: 카드 표시용 값. 현재 목록 API 명세에는 없는 필드라 없으면 카드에서 생략됨
 * - 카테고리 분포: 카페/디저트 6 · 한식 7 · 양식 6 · 베이커리 6 · 기타 5
 */
export const DUMMY_STORES = [
  {
    id: 1,
    name: '루키즈 베이커리 & 카페',
    category: '베이커리',
    address: '서울시 강남구 테헤란로 123 1층',
    storePhone: '02-555-1234',
    openTime: '08:30',
    closeTime: '21:00',
    description: '매일 아침 갓 구워내는 천연 발효종 소금빵과 스페셜티 커피 전문점입니다.',
    imageUrl: null,
    rating: 4.9,
    reviewCount: 128,
  },
  {
    id: 2,
    name: '감성 커피 하우스',
    category: '카페/디저트',
    address: '서울시 강남구 역삼로 45',
    storePhone: '02-555-2345',
    openTime: '10:00',
    closeTime: '22:00',
    description: '직접 로스팅한 원두로 내리는 핸드드립 커피',
    imageUrl: null,
    rating: 4.8,
    reviewCount: 95,
  },
  {
    id: 3,
    name: '엄마손 한식당',
    category: '한식',
    address: '서울시 강남구 선릉로 88 2층',
    storePhone: '02-555-3456',
    openTime: '11:00',
    closeTime: '21:30',
    description: '집밥처럼 정성껏 끓인 찌개와 반찬 정식',
    imageUrl: null,
    rating: 4.6,
    reviewCount: 212,
  },
  {
    id: 4,
    name: '트라토리아 루키',
    category: '양식',
    address: '서울시 강남구 테헤란로 210',
    storePhone: '02-555-4567',
    openTime: '11:30',
    closeTime: '22:00',
    description: '생면 파스타와 화덕 피자를 즐기는 이탈리안 비스트로',
    imageUrl: null,
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: 5,
    name: '달콤 디저트 공방',
    category: '카페/디저트',
    address: '서울시 강남구 봉은사로 17',
    storePhone: '02-555-5678',
    openTime: '12:00',
    closeTime: '20:00',
    description: '수제 케이크와 구움과자를 매일 소량 생산합니다',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 41,
  },
  {
    id: 6,
    name: '동네 반찬가게',
    category: '기타',
    address: '서울시 강남구 언주로 302',
    storePhone: '02-555-6789',
    openTime: '07:00',
    closeTime: '19:00',
    description: '매일 새로 만드는 동네 반찬과 밑반찬 포장 전문',
    imageUrl: null,
    rating: 4.4,
    reviewCount: 27,
  },
  {
    id: 7,
    name: '온기 국밥',
    category: '한식',
    address: '서울시 강남구 논현로 512',
    storePhone: '02-555-7001',
    openTime: '06:00',
    closeTime: '22:00',
    description: '24시간 우려낸 사골 육수로 끓이는 순대국밥',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 176,
  },
  {
    id: 8,
    name: '브루클린 버거 랩',
    category: '양식',
    address: '서울시 강남구 강남대로 396',
    storePhone: '02-555-7002',
    openTime: '11:00',
    closeTime: '21:00',
    description: '매장에서 직접 다진 패티로 만드는 수제 버거',
    imageUrl: null,
    rating: 4.3,
    reviewCount: 88,
  },
  {
    id: 9,
    name: '밀과 버터',
    category: '베이커리',
    address: '서울시 강남구 도산대로 145',
    storePhone: '02-555-7003',
    openTime: '08:00',
    closeTime: '20:00',
    description: '프랑스산 버터로 굽는 크루아상과 페이스트리',
    imageUrl: null,
    rating: 4.8,
    reviewCount: 203,
  },
  {
    id: 10,
    name: '티타임 스튜디오',
    category: '카페/디저트',
    address: '서울시 강남구 압구정로 29길 12',
    storePhone: '02-555-7004',
    openTime: '11:00',
    closeTime: '21:00',
    description: '계절 티와 스콘을 함께 즐기는 티룸',
    imageUrl: null,
    rating: 4.6,
    reviewCount: 52,
  },
  {
    id: 11,
    name: '할매 손칼국수',
    category: '한식',
    address: '서울시 강남구 개포로 620',
    storePhone: '02-555-7005',
    openTime: '10:30',
    closeTime: '20:30',
    description: '직접 반죽해 뽑은 면과 바지락 육수',
    imageUrl: null,
    rating: 4.7,
    reviewCount: 311,
  },
  {
    id: 12,
    name: '르 쁘띠 비스트로 강남 테헤란로 본점',
    category: '양식',
    address: '서울시 강남구 테헤란로 427 위워크타워 1층',
    storePhone: '02-555-7006',
    openTime: '17:00',
    closeTime: '23:30',
    description: '가게명·주소가 긴 경우의 말줄임 표시를 확인하기 위한 매장입니다. 저녁에만 여는 프렌치 비스트로',
    imageUrl: null,
    rating: 4.4,
    reviewCount: 19,
  },
  {
    id: 13,
    name: '아침 빵집',
    category: '베이커리',
    address: '서울시 강남구 영동대로 85길 7',
    storePhone: '02-555-7007',
    openTime: '06:30',
    closeTime: '14:00',
    description: '오전에만 여는 식빵·베이글 전문점',
    imageUrl: null,
    rating: 4.2,
    reviewCount: 34,
  },
  {
    id: 14,
    name: '꽃길 꽃집',
    category: '기타',
    address: '서울시 강남구 학동로 171',
    storePhone: '02-555-7008',
    openTime: '09:00',
    closeTime: '19:00',
    description: '미리 주문하고 픽업하는 꽃다발 · 꽃바구니',
    imageUrl: null,
    rating: 4.9,
    reviewCount: 61,
  },
  {
    id: 15,
    name: '젤라또 피아노',
    category: '카페/디저트',
    address: '서울시 강남구 신사동 가로수길 33',
    storePhone: '02-555-7009',
    openTime: '12:00',
    closeTime: '23:00',
    description: '매일 아침 만드는 이탈리아식 젤라또 12가지 맛',
    imageUrl: null,
    rating: 4.7,
    reviewCount: 142,
  },
  {
    id: 16,
    name: '돌솥 비빔밥 명가',
    category: '한식',
    address: '서울시 강남구 삼성로 530',
    storePhone: '02-555-7010',
    openTime: '11:00',
    closeTime: '21:00',
    description: '제철 나물과 돌솥에 지은 밥',
    imageUrl: null,
    rating: 4.1,
    reviewCount: 45,
  },
  {
    id: 17,
    name: '스테이크 하우스 루키',
    category: '양식',
    address: '서울시 강남구 선릉로 158길 11',
    storePhone: '02-555-7011',
    openTime: '17:30',
    closeTime: '22:30',
    description: '드라이에이징 스테이크와 와인 페어링',
    imageUrl: null,
    rating: 4.8,
    reviewCount: 97,
  },
  {
    id: 18,
    name: '천연발효 캄파뉴',
    category: '베이커리',
    address: '서울시 강남구 봉은사로 68길 4',
    storePhone: '02-555-7012',
    openTime: '09:00',
    closeTime: '19:00',
    description: '유기농 통밀로 48시간 발효한 캄파뉴',
    imageUrl: null,
    rating: 4.6,
    reviewCount: 73,
  },
  {
    id: 19,
    name: '심야 떡볶이',
    category: '기타',
    address: '서울시 강남구 강남대로 94길 20',
    storePhone: '02-555-7013',
    openTime: '18:00',
    closeTime: '02:00',
    description: '자정을 넘겨 영업하는 분식집 (영업 상태 계산 테스트용)',
    imageUrl: null,
    rating: 4.3,
    reviewCount: 158,
  },
  {
    id: 20,
    name: '마카롱 아틀리에',
    category: '카페/디저트',
    address: '서울시 강남구 도곡로 205',
    storePhone: '02-555-7014',
    openTime: '11:00',
    closeTime: '20:00',
    description: '프랑스식 꼬끄에 제철 과일 필링',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 66,
  },
  {
    id: 21,
    name: '청담 한우 곰탕',
    category: '한식',
    address: '서울시 강남구 청담동 도산대로 510',
    storePhone: '02-555-7015',
    openTime: '07:00',
    closeTime: '15:00',
    description: '한우 양지로 맑게 끓인 곰탕, 점심 전 품절 주의',
    imageUrl: null,
    rating: 4.9,
    reviewCount: 402,
  },
  {
    id: 22,
    name: '파스타 공장',
    category: '양식',
    address: '서울시 강남구 역삼로 17길 30',
    storePhone: '02-555-7016',
    openTime: '11:00',
    closeTime: '21:30',
    description: '1인 파스타 세트와 포장 전용 메뉴',
    imageUrl: null,
    rating: 4.0,
    reviewCount: 38,
  },
  {
    id: 23,
    name: '베이글 연구소',
    category: '베이커리',
    address: '서울시 강남구 논현로 85길 19',
    storePhone: '02-555-7017',
    openTime: '08:00',
    closeTime: '18:00',
    description: '쫄깃한 뉴욕식 베이글과 수제 크림치즈',
    imageUrl: null,
    rating: 4.7,
    reviewCount: 189,
  },
  {
    id: 24,
    name: '과일 가게 싱싱',
    category: '기타',
    address: '서울시 강남구 개포로 22길 8',
    storePhone: '02-555-7018',
    openTime: '09:00',
    closeTime: '21:00',
    description: '오늘 들어온 제철 과일 소분 포장',
    imageUrl: null,
    rating: 4.2,
    reviewCount: 23,
  },
  {
    id: 25,
    name: '와플 앤 크로플',
    category: '카페/디저트',
    address: '서울시 강남구 테헤란로 8길 21',
    storePhone: '02-555-7019',
    openTime: '10:00',
    closeTime: '22:00',
    description: '겉바속촉 크로플과 벨기에 와플',
    imageUrl: null,
    rating: 4.4,
    reviewCount: 81,
  },
  {
    id: 26,
    name: '제주 고기국수',
    category: '한식',
    address: '서울시 강남구 역삼동 논현로 330',
    storePhone: '02-555-7020',
    openTime: '11:00',
    closeTime: '22:00',
    description: '돼지 사골 육수에 수육을 듬뿍 올린 고기국수',
    imageUrl: null,
    rating: 4.6,
    reviewCount: 119,
  },
  {
    id: 27,
    name: '멕시칸 타코 스탠드',
    category: '양식',
    address: '서울시 강남구 신사동 압구정로 10길 5',
    storePhone: '02-555-7021',
    openTime: '11:30',
    closeTime: '21:00',
    description: '또띠아를 매장에서 직접 굽는 타코·부리또',
    imageUrl: null,
    rating: 4.3,
    reviewCount: 57,
  },
  {
    id: 28,
    name: '단팥빵 연구소',
    category: '베이커리',
    address: '서울시 강남구 삼성로 96길 14',
    storePhone: '02-555-7022',
    openTime: '10:00',
    closeTime: '19:00',
    description: '국산 팥을 직접 쑤어 만든 단팥빵과 앙버터',
    imageUrl: null,
    rating: 4.5,
    reviewCount: 92,
  },
  {
    id: 29,
    name: '동네 세탁소',
    category: '기타',
    address: '서울시 강남구 선릉로 93길 27',
    storePhone: '02-555-7023',
    openTime: '08:00',
    closeTime: '20:00',
    description: '미리 접수하고 찾아가는 세탁 · 수선 픽업',
    imageUrl: null,
    rating: 4.1,
    reviewCount: 14,
  },
  {
    id: 30,
    name: '보리밥 정식',
    category: '한식',
    address: '서울시 강남구 언주로 164길 3',
    storePhone: '02-555-7024',
    openTime: '11:00',
    closeTime: '20:00',
    description: '보리밥에 강된장과 제철 나물 여덟 가지',
    imageUrl: null,
    rating: 4.4,
    reviewCount: 68,
  },
];
