/**
 * 백엔드 연동 전 화면 개발용 더미 매장 데이터 (총 30개 — 페이지네이션·카테고리 필터 테스트용)
 * storeApi.js의 USE_DUMMY를 true로 바꾸면 이 데이터를 사용합니다.
 *
 * - 필드는 백엔드 StoreResponse 기준(id, name, category, address, openTime, closeTime)에
 *   화면 확인용 storePhone, description, imageUrl을 더한 형태 (백엔드 응답엔 이 세 필드가 없음)
 * - category: 백엔드 매장 카테고리 값과 동일 — 베이커리 / 카페 / 분식 / 일식 / 치킨 (각 6개)
 * - id 1: 1차 기획 문서 dummy_data.sql의 1번 매장 값, id 2~30: 테스트용 가상 매장
 * - imageUrl: 전부 null — 이미지가 없을 때 카드의 플레이스홀더 처리를 확인하기 위함
 * - 테스트용 특수 매장: id 12(가게명·주소가 긴 경우), id 19·29(자정을 넘기는 영업시간)
 */
export const DUMMY_STORES = [
  {
    id: 1,
    name: '루키즈 베이커리 & 카페',
    category: '베이커리',
    address: '서울시 강남구 테헤란로 123 1층',
    storePhone: '02-555-1234',
    openTime: '08:30',
    closeTime: '21:00',
    description: '매일 아침 갓 구워내는 천연 발효종 소금빵과 스페셜티 커피 전문점입니다.',
    imageUrl: null,
  },
  {
    id: 2,
    name: '감성 커피 하우스',
    category: '카페',
    address: '서울시 강남구 역삼로 45',
    storePhone: '02-555-2345',
    openTime: '10:00',
    closeTime: '22:00',
    description: '직접 로스팅한 원두로 내리는 핸드드립 커피',
    imageUrl: null,
  },
  {
    id: 3,
    name: '엄마손 분식',
    category: '분식',
    address: '서울시 강남구 선릉로 88 2층',
    storePhone: '02-555-3456',
    openTime: '11:00',
    closeTime: '21:30',
    description: '국물 떡볶이와 꼬마김밥 세트',
    imageUrl: null,
  },
  {
    id: 4,
    name: '스시 루키',
    category: '일식',
    address: '서울시 강남구 테헤란로 210',
    storePhone: '02-555-4567',
    openTime: '11:30',
    closeTime: '22:00',
    description: '오늘 들어온 생선으로 쥐는 초밥 세트',
    imageUrl: null,
  },
  {
    id: 5,
    name: '달콤 디저트 공방',
    category: '카페',
    address: '서울시 강남구 봉은사로 17',
    storePhone: '02-555-5678',
    openTime: '12:00',
    closeTime: '20:00',
    description: '수제 케이크와 구움과자를 매일 소량 생산합니다',
    imageUrl: null,
  },
  {
    id: 6,
    name: '동네 옛날통닭',
    category: '치킨',
    address: '서울시 강남구 언주로 302',
    storePhone: '02-555-6789',
    openTime: '15:00',
    closeTime: '23:00',
    description: '가마솥에 튀기는 옛날 통닭',
    imageUrl: null,
  },
  {
    id: 7,
    name: '온기 김밥',
    category: '분식',
    address: '서울시 강남구 논현로 512',
    storePhone: '02-555-7001',
    openTime: '06:00',
    closeTime: '22:00',
    description: '매일 아침 새로 싸는 참치·치즈 김밥',
    imageUrl: null,
  },
  {
    id: 8,
    name: '크리스피 치킨 랩',
    category: '치킨',
    address: '서울시 강남구 강남대로 396',
    storePhone: '02-555-7002',
    openTime: '11:00',
    closeTime: '21:00',
    description: '바삭한 크리스피 치킨과 치킨버거',
    imageUrl: null,
  },
  {
    id: 9,
    name: '밀과 버터',
    category: '베이커리',
    address: '서울시 강남구 도산대로 145',
    storePhone: '02-555-7003',
    openTime: '08:00',
    closeTime: '20:00',
    description: '프랑스산 버터로 굽는 크루아상과 페이스트리',
    imageUrl: null,
  },
  {
    id: 10,
    name: '티타임 스튜디오',
    category: '카페',
    address: '서울시 강남구 압구정로 29길 12',
    storePhone: '02-555-7004',
    openTime: '11:00',
    closeTime: '21:00',
    description: '계절 티와 스콘을 함께 즐기는 티룸',
    imageUrl: null,
  },
  {
    id: 11,
    name: '할매 손칼국수',
    category: '분식',
    address: '서울시 강남구 개포로 620',
    storePhone: '02-555-7005',
    openTime: '10:30',
    closeTime: '20:30',
    description: '직접 반죽해 뽑은 면과 바지락 육수',
    imageUrl: null,
  },
  {
    id: 12,
    name: '하쿠나 돈카츠 & 우동 강남 테헤란로 본점',
    category: '일식',
    address: '서울시 강남구 테헤란로 427 위워크타워 1층',
    storePhone: '02-555-7006',
    openTime: '17:00',
    closeTime: '23:30',
    description: '가게명·주소가 긴 경우의 말줄임 표시를 확인하기 위한 매장입니다. 두툼한 로스카츠와 우동 세트',
    imageUrl: null,
  },
  {
    id: 13,
    name: '아침 빵집',
    category: '베이커리',
    address: '서울시 강남구 영동대로 85길 7',
    storePhone: '02-555-7007',
    openTime: '06:30',
    closeTime: '14:00',
    description: '오전에만 여는 식빵·베이글 전문점',
    imageUrl: null,
  },
  {
    id: 14,
    name: '꽃길 양념치킨',
    category: '치킨',
    address: '서울시 강남구 학동로 171',
    storePhone: '02-555-7008',
    openTime: '14:00',
    closeTime: '23:00',
    description: '달콤한 수제 양념치킨',
    imageUrl: null,
  },
  {
    id: 15,
    name: '젤라또 피아노',
    category: '카페',
    address: '서울시 강남구 신사동 가로수길 33',
    storePhone: '02-555-7009',
    openTime: '12:00',
    closeTime: '23:00',
    description: '매일 아침 만드는 이탈리아식 젤라또 12가지 맛',
    imageUrl: null,
  },
  {
    id: 16,
    name: '규동 한 그릇',
    category: '일식',
    address: '서울시 강남구 삼성로 530',
    storePhone: '02-555-7010',
    openTime: '11:00',
    closeTime: '21:00',
    description: '달콤짭짤한 소고기 덮밥',
    imageUrl: null,
  },
  {
    id: 17,
    name: '숯불 치킨 하우스',
    category: '치킨',
    address: '서울시 강남구 선릉로 158길 11',
    storePhone: '02-555-7011',
    openTime: '17:30',
    closeTime: '22:30',
    description: '숯불에 구운 순살 치킨',
    imageUrl: null,
  },
  {
    id: 18,
    name: '천연발효 캄파뉴',
    category: '베이커리',
    address: '서울시 강남구 봉은사로 68길 4',
    storePhone: '02-555-7012',
    openTime: '09:00',
    closeTime: '19:00',
    description: '유기농 통밀로 48시간 발효한 캄파뉴',
    imageUrl: null,
  },
  {
    id: 19,
    name: '심야 떡볶이',
    category: '분식',
    address: '서울시 강남구 강남대로 94길 20',
    storePhone: '02-555-7013',
    openTime: '18:00',
    closeTime: '02:00',
    description: '자정을 넘겨 영업하는 분식집 (영업 상태 계산 테스트용)',
    imageUrl: null,
  },
  {
    id: 20,
    name: '마카롱 아틀리에',
    category: '카페',
    address: '서울시 강남구 도곡로 205',
    storePhone: '02-555-7014',
    openTime: '11:00',
    closeTime: '20:00',
    description: '프랑스식 꼬끄에 제철 과일 필링',
    imageUrl: null,
  },
  {
    id: 21,
    name: '청담 간장치킨',
    category: '치킨',
    address: '서울시 강남구 청담동 도산대로 510',
    storePhone: '02-555-7015',
    openTime: '15:00',
    closeTime: '23:30',
    description: '마늘 간장 소스 치킨',
    imageUrl: null,
  },
  {
    id: 22,
    name: '라멘 공장',
    category: '일식',
    address: '서울시 강남구 역삼로 17길 30',
    storePhone: '02-555-7016',
    openTime: '11:00',
    closeTime: '21:30',
    description: '진한 돈코츠 라멘과 차슈 추가',
    imageUrl: null,
  },
  {
    id: 23,
    name: '베이글 연구소',
    category: '베이커리',
    address: '서울시 강남구 논현로 85길 19',
    storePhone: '02-555-7017',
    openTime: '08:00',
    closeTime: '18:00',
    description: '쫄깃한 뉴욕식 베이글과 수제 크림치즈',
    imageUrl: null,
  },
  {
    id: 24,
    name: '싱싱 순대',
    category: '분식',
    address: '서울시 강남구 개포로 22길 8',
    storePhone: '02-555-7018',
    openTime: '09:00',
    closeTime: '21:00',
    description: '찰순대와 모둠 내장 포장 전문',
    imageUrl: null,
  },
  {
    id: 25,
    name: '와플 앤 크로플',
    category: '카페',
    address: '서울시 강남구 테헤란로 8길 21',
    storePhone: '02-555-7019',
    openTime: '10:00',
    closeTime: '22:00',
    description: '겉바속촉 크로플과 벨기에 와플',
    imageUrl: null,
  },
  {
    id: 26,
    name: '우동 명가',
    category: '일식',
    address: '서울시 강남구 역삼동 논현로 330',
    storePhone: '02-555-7020',
    openTime: '11:00',
    closeTime: '22:00',
    description: '직접 뽑은 사누키 우동',
    imageUrl: null,
  },
  {
    id: 27,
    name: '오니기리 스탠드',
    category: '일식',
    address: '서울시 강남구 신사동 압구정로 10길 5',
    storePhone: '02-555-7021',
    openTime: '11:30',
    closeTime: '21:00',
    description: '즉석에서 만드는 주먹밥과 미소국',
    imageUrl: null,
  },
  {
    id: 28,
    name: '단팥빵 연구소',
    category: '베이커리',
    address: '서울시 강남구 삼성로 96길 14',
    storePhone: '02-555-7022',
    openTime: '10:00',
    closeTime: '19:00',
    description: '국산 팥을 직접 쑤어 만든 단팥빵과 앙버터',
    imageUrl: null,
  },
  {
    id: 29,
    name: '치킨 앤 맥주',
    category: '치킨',
    address: '서울시 강남구 선릉로 93길 27',
    storePhone: '02-555-7023',
    openTime: '17:00',
    closeTime: '01:00',
    description: '반반 치킨과 수제 맥주',
    imageUrl: null,
  },
  {
    id: 30,
    name: '라볶이 공방',
    category: '분식',
    address: '서울시 강남구 언주로 164길 3',
    storePhone: '02-555-7024',
    openTime: '11:00',
    closeTime: '20:00',
    description: '라면사리 듬뿍 넣은 즉석 라볶이',
    imageUrl: null,
  },
];
